export const LOGIN = "LOGIN";
export const REGISTRATION = "REGISTRATION";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const GET_ACCOUNT_INFO = "GET_ACCOUNT_INFO";
export const GET_STOCKS = "GET_STOCKS";
export const GET_STOCK_HISTORY = "GET_STOCK_HISTORY";
export const CREATE_SELL = "CREATE_SELL";
export const CREATE_BUY = "CREATE_BUY";
export const GET_TRANSACTION_HISTORY = "GET_TRANSACTION_HISTORY";


export const OPEN_TRANSACTION_HISTORY_VIEW = "OPEN_TRANSACTION_HISTORY_VIEW";
export const OPEN_ACCOUNT_INFO_VIEW = "OPEN_ACCOUNT_INFO_VIEW";
export const START_STOCKS_HISTORY_LOADER = "START_STOCKS_HISTORY_LOADER";

export const SUCCESS_EVENT = '_SUCCESS';
export const FAIL_EVENT = '_FAIL';
export const INPROCESS_EVENT = '_INPROCESS';


export const START_SELL = "START_SELL";
export const START_BUY = "START_BUY";
export const COMPLETE_SELL = "COMPLETE_SELL";
export const COMPLETE_BUY = "COMPLETE_BUY";